version: 1

formatters:
  simple:
    format: "%(asctime)s %(levelname)s: %(message)s"
    datefmt: "%a %b %d %I:%M:%S %p"
  extended:
    format: "%(asctime)s %(name)s %(levelname)s: %(message)s"

handlers:
  console:
    level: ERROR
    class: logging.StreamHandler
    stream: ext://sys.stdout
    formatter: simple
  logfile:
    level: DEBUG
    class: logging.FileHandler
    filename: log_hvac.log
    formatter: extended

loggers:
  bacnet_controllers:
    level: INFO
    handlers: [console, logfile]
    propagate: False
  bacnet_table:
    level: INFO
    handlers: [console, logfile]
    propagate: False

root:
  level: DEBUG
  handlers: [console, logfile]
  disable_existing_loggers: True  # Default=True.
